apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: greetings
spec:
  template:
    metadata:
      labels:
        app: greetings
    spec:
      containers:
        - name: greetings
          image: greetings
          imagePullPolicy: "Never"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: greetings
spec:
  type: NodePort
  ports:
    - nodePort: 31310
      port: 8080
      protocol: TCP
  selector:
    app: greetings